version: '3.11'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  # Edge port for all services
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./localstack-data:/tmp/localstack/data 